import { FrequencyChoices } from "../../../../src/independent-worker/schemas";
import { IndependentWorkerTestScenario } from "../../types";

// Helper function to create dates relative to current year
const getCurrentYear = () => new Date().getFullYear();
const getDateInCurrentYear = (month: number, day: number = 1) => new Date(getCurrentYear(), month - 1, day);
const getDateInPreviousYear = (month: number, day: number = 1) => new Date(getCurrentYear() - 1, month - 1, day);
const getDateMonthsAgo = (monthsAgo: number) => {
  const date = new Date();
  date.setMonth(date.getMonth() - monthsAgo);
  return date;
};

export const businessOpeningScenarios: IndependentWorkerTestScenario[] = [
  // ============================================================
  // FIRST YEAR BENEFITS - Newly opened activity (within first 12 months)
  // ============================================================

  // Basic first year scenarios with different income levels
  {
    name: "First year - Low income €15,000 opened in January",
    observations: "Activity opened January 1st of current year - within first financial year and first 12 months (SS exempt)",
    params: {
      income: 15000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year - Standard income €30,000 opened in January",
    observations: "Activity opened January 1st - first financial year, SS exempt for first 12 months",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year - High income €50,000 opened in January",
    observations: "High income in first year - testing first year benefits with higher brackets",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // FIRST YEAR BENEFITS - Different opening dates throughout the year
  // ============================================================

  {
    name: "First year - Activity opened mid-year (June 15th)",
    observations: "Activity opened mid-year - still within first financial year and first 12 months",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(6, 15),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year - Activity opened late in year (October 1st)",
    observations: "Activity opened late in year - first financial year, still within first 12 months",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(10, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year - Activity opened very late (December 31st)",
    observations: "Activity opened on last day of year - edge case for first financial year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(12, 31),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year - Activity opened 6 months ago",
    observations: "Activity opened 6 months ago - still within first 12 months (SS exempt)",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateMonthsAgo(6),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year - Activity opened 11 months ago",
    observations: "Activity opened 11 months ago - still within first 12 months (SS exempt)",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateMonthsAgo(11),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // FIRST YEAR BENEFITS - First year + Youth IRS combinations
  // ============================================================

  {
    name: "First year + Youth IRS year 1 - €20,000 income",
    observations: "First year benefits combined with Youth IRS first year (50% discount)",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year + Youth IRS year 2 - €25,000 income",
    observations: "First year benefits combined with Youth IRS second year (25% discount)",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "First year + Youth IRS year 3 - €30,000 income",
    observations: "First year benefits combined with Youth IRS third year (no discount)",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 3,
    },
  },
  {
    name: "First year + Youth IRS year 1 - High income €40,000",
    observations: "First year + Youth IRS year 1 with higher income - testing benefit limits",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year + Youth IRS year 2 - Mid-year opening",
    observations: "First year + Youth IRS year 2 with activity opened mid-year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(6, 15),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // ============================================================
  // FIRST YEAR BENEFITS - First year + RNH combinations
  // ============================================================

  {
    name: "First year + RNH - €30,000 income",
    observations: "First year benefits combined with RNH regime (20% flat rate)",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year + RNH - €40,000 income",
    observations: "First year + RNH with higher income - testing RNH flat rate benefit",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year + RNH - €60,000 income",
    observations: "First year + RNH with very high income - RNH becomes more beneficial",
    params: {
      income: 60000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year + RNH - Mid-year opening",
    observations: "First year + RNH with activity opened mid-year",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(6, 15),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // FIRST YEAR BENEFITS - First year + RNH + Youth IRS combinations
  // ============================================================

  {
    name: "First year + RNH + Youth IRS year 1 - €30,000 income",
    observations: "All benefits combined: first year + RNH + Youth IRS year 1",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "First year + RNH + Youth IRS year 2 - €40,000 income",
    observations: "All benefits combined: first year + RNH + Youth IRS year 2",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // ============================================================
  // SECOND YEAR BENEFITS - Second financial year scenarios
  // ============================================================

  {
    name: "Second year - Low income €15,000 opened January previous year",
    observations: "Activity opened January 1st of previous year - second financial year, SS payments apply",
    params: {
      income: 15000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Second year - Standard income €30,000 opened January previous year",
    observations: "Activity opened January 1st previous year - second financial year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Second year - High income €50,000 opened January previous year",
    observations: "High income in second year - testing second year benefits with higher brackets",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Second year - Activity opened mid-year previous year (June 15th)",
    observations: "Activity opened mid-year previous year - second financial year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(6, 15),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Second year - Activity opened late previous year (December 31st)",
    observations: "Activity opened last day of previous year - second financial year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(12, 31),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // SECOND YEAR BENEFITS - Second year + other benefits combinations
  // ============================================================

  {
    name: "Second year + Youth IRS year 1 - €20,000 income",
    observations: "Second year benefits combined with Youth IRS first year (50% discount)",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Second year + Youth IRS year 2 - €30,000 income",
    observations: "Second year benefits combined with Youth IRS second year (25% discount)",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Second year + RNH - €40,000 income",
    observations: "Second year benefits combined with RNH regime (20% flat rate)",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Second year + RNH + Youth IRS year 1 - €35,000 income",
    observations: "Second year + RNH + Youth IRS year 1 - all benefits combined",
    params: {
      income: 35000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Second year + Organized expenses €8,000 - €30,000 income",
    observations: "Second year with organized accounting expenses",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 8000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // EDGE CASES - Activity opened mid-year scenarios
  // ============================================================

  {
    name: "Edge case - Activity opened exactly 12 months ago",
    observations: "Activity opened exactly 12 months ago - boundary between first 12 months and beyond",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateMonthsAgo(12),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Edge case - Activity opened 13 months ago (previous year)",
    observations: "Activity opened 13 months ago - beyond first 12 months, in second financial year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateMonthsAgo(13),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Edge case - Activity opened 18 months ago",
    observations: "Activity opened 18 months ago - well beyond first 12 months, second financial year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateMonthsAgo(18),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // EDGE CASES - Activity opened late in year scenarios
  // ============================================================

  {
    name: "Edge case - Activity opened December 31st current year",
    observations: "Activity opened on last day of current year - first financial year, within first 12 months",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(12, 31),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Edge case - Activity opened December 31st previous year",
    observations: "Activity opened last day of previous year - second financial year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(12, 31),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // EDGE CASES - Multiple year transitions and complex scenarios
  // ============================================================

  {
    name: "Edge case - First year with monthly income €2,000",
    observations: "First year benefits with monthly frequency",
    params: {
      income: 2000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Edge case - First year with daily rate €100, 30 days off",
    observations: "First year benefits with daily frequency",
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 30,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Edge case - Second year with monthly income €3,000",
    observations: "Second year benefits with monthly frequency",
    params: {
      income: 3000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Edge case - First year + High expenses €10,000 - €40,000 income",
    observations: "First year benefits with organized accounting expenses",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 10000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInCurrentYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Edge case - Second year + High expenses €12,000 - €50,000 income",
    observations: "Second year benefits with organized accounting expenses",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 12000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: getDateInPreviousYear(1, 1),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
];

