import { FrequencyChoices } from "../../../../src/independent-worker/schemas";
import { IndependentWorkerTestScenario } from "../../types";

export const youthIrsScenarios: IndependentWorkerTestScenario[] = [
  // ============================================================
  // DIFFERENT BENEFIT YEARS - 2025 Tax Year
  // ============================================================

  // 1st Year Benefits (100% discount for 2025)
  {
    name: "Youth IRS 1st year with €10,000 income - 100% discount (2025)",
    observations: "First year of Youth IRS benefits - maximum discount (100%) for 2025 tax year",
    params: {
      income: 10000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Youth IRS 1st year with €15,000 income - 100% discount (2025)",
    observations: "First year benefits with low income - testing maximum discount impact",
    params: {
      income: 15000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Youth IRS 1st year with €20,000 income - 100% discount (2025)",
    observations: "First year benefits with medium income",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Youth IRS 1st year with €30,000 income - 100% discount (2025)",
    observations: "First year benefits with higher income - testing discount limits",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Youth IRS 1st year with €50,000 income - 100% discount (2025)",
    observations: "First year benefits with high income - testing IAS multiplier limits",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },

  // 2nd Year Benefits (75% discount for 2025)
  {
    name: "Youth IRS 2nd year with €10,000 income - 75% discount (2025)",
    observations: "Second year of Youth IRS benefits - 75% discount for 2025 tax year",
    params: {
      income: 10000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Youth IRS 2nd year with €15,000 income - 75% discount (2025)",
    observations: "Second year benefits - existing basic scenario",
    params: {
      income: 15000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Youth IRS 2nd year with €20,000 income - 75% discount (2025)",
    observations: "Second year benefits with medium income",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Youth IRS 2nd year with €25,000 income - 75% discount (2025)",
    observations: "Second year benefits with experienced freelancer income",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Youth IRS 2nd year with €30,000 income - 75% discount (2025)",
    observations: "Second year benefits with mid-level consultant income",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Youth IRS 2nd year with €40,000 income - 75% discount (2025)",
    observations: "Second year benefits with high income",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Youth IRS 2nd year with €50,000 income - 75% discount (2025)",
    observations: "Second year benefits with very high income - testing discount limits",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // 3rd Year Benefits (75% discount for 2025 - same as 2nd year)
  {
    name: "Youth IRS 3rd year with €15,000 income - 75% discount (2025)",
    observations: "Third year of Youth IRS benefits - 75% discount (same as 2nd year for 2025)",
    params: {
      income: 15000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 3,
    },
  },
  {
    name: "Youth IRS 3rd year with €20,000 income - 75% discount (2025)",
    observations: "Third year benefits - transition from 2nd year with same discount",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 3,
    },
  },
  {
    name: "Youth IRS 3rd year with €30,000 income - 75% discount (2025)",
    observations: "Third year benefits with higher income",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 3,
    },
  },
  {
    name: "Youth IRS 3rd year with €40,000 income - 75% discount (2025)",
    observations: "Third year benefits with high income - testing transition scenarios",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 3,
    },
  },

  // 4th Year Benefits (75% discount for 2025 - same as 2nd and 3rd)
  {
    name: "Youth IRS 4th year with €20,000 income - 75% discount (2025)",
    observations: "Fourth year of Youth IRS benefits - still 75% discount for 2025",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 4,
    },
  },
  {
    name: "Youth IRS 4th year with €30,000 income - 75% discount (2025)",
    observations: "Fourth year benefits - maintaining 75% discount",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 4,
    },
  },

  // 5th Year Benefits (50% discount for 2025 - transition to lower discount)
  {
    name: "Youth IRS 5th year with €20,000 income - 50% discount (2025)",
    observations: "Fifth year of Youth IRS benefits - transition to 50% discount",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 5,
    },
  },
  {
    name: "Youth IRS 5th year with €30,000 income - 50% discount (2025)",
    observations: "Fifth year benefits - testing discount reduction impact",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 5,
    },
  },
  {
    name: "Youth IRS 5th year with €40,000 income - 50% discount (2025)",
    observations: "Fifth year benefits with higher income",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 5,
    },
  },
  {
    name: "Youth IRS 5th year with €50,000 income - 50% discount (2025)",
    observations: "Fifth year benefits with high income",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 5,
    },
  },

  // 6th and 7th Year Benefits (50% discount for 2025)
  {
    name: "Youth IRS 6th year with €25,000 income - 50% discount (2025)",
    observations: "Sixth year benefits - maintaining 50% discount",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 6,
    },
  },
  {
    name: "Youth IRS 7th year with €30,000 income - 50% discount (2025)",
    observations: "Seventh year benefits - last year with 50% discount",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 7,
    },
  },

  // 8th-10th Year Benefits (25% discount for 2025 - final years)
  {
    name: "Youth IRS 8th year with €25,000 income - 25% discount (2025)",
    observations: "Eighth year benefits - transition to 25% discount",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 8,
    },
  },
  {
    name: "Youth IRS 9th year with €30,000 income - 25% discount (2025)",
    observations: "Ninth year benefits - maintaining 25% discount",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 9,
    },
  },
  {
    name: "Youth IRS 10th year with €35,000 income - 25% discount (2025)",
    observations: "Tenth year benefits - final year of Youth IRS benefits",
    params: {
      income: 35000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 10,
    },
  },

  // ============================================================
  // INCOME LEVEL COMBINATIONS - Comprehensive Coverage
  // ============================================================

  // Low Income + Youth IRS (€10,000)
  {
    name: "Low income €10,000 with Youth IRS 1st year benefits",
    observations: "Very low income with maximum Youth IRS benefits",
    params: {
      income: 10000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Low income €10,000 with Youth IRS 2nd year benefits",
    observations: "Very low income with 75% Youth IRS discount",
    params: {
      income: 10000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // Medium Income + Youth IRS (€20,000, €25,000, €30,000)
  {
    name: "Medium income €20,000 with Youth IRS 1st year benefits",
    observations: "Standard freelancer income with maximum Youth IRS benefits",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Medium income €20,000 with Youth IRS 2nd year benefits",
    observations: "Standard freelancer income with 75% Youth IRS discount",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Medium income €25,000 with Youth IRS 1st year benefits",
    observations: "Experienced freelancer income with maximum Youth IRS benefits",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Medium income €25,000 with Youth IRS 2nd year benefits",
    observations: "Experienced freelancer income with 75% Youth IRS discount",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Medium income €30,000 with Youth IRS 1st year benefits",
    observations: "Mid-level consultant income with maximum Youth IRS benefits",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Medium income €30,000 with Youth IRS 2nd year benefits",
    observations: "Mid-level consultant income with 75% Youth IRS discount",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // High Income + Youth IRS (€40,000, €50,000)
  {
    name: "High income €40,000 with Youth IRS 1st year benefits",
    observations: "High income with maximum Youth IRS benefits - testing discount limits",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "High income €40,000 with Youth IRS 2nd year benefits",
    observations: "High income with 75% Youth IRS discount",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "High income €50,000 with Youth IRS 1st year benefits",
    observations: "Very high income with maximum Youth IRS benefits - testing IAS multiplier limits",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "High income €50,000 with Youth IRS 2nd year benefits",
    observations: "Very high income with 75% Youth IRS discount",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // Maximum Youth IRS benefit scenarios - testing IAS multiplier limits
  {
    name: "Maximum Youth IRS benefit - €60,000 income with 1st year benefits",
    observations: "Testing maximum discount with high income - IAS multiplier may limit discount",
    params: {
      income: 60000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Maximum Youth IRS benefit - €80,000 income with 1st year benefits",
    observations: "Very high income - testing where IAS multiplier becomes the limiting factor",
    params: {
      income: 80000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Maximum Youth IRS benefit - €100,000 income with 1st year benefits",
    observations: "Maximum income scenario - IAS multiplier should limit discount",
    params: {
      income: 100000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // EDGE CASES
  // ============================================================

  // Income above Youth IRS maximum benefit threshold
  {
    name: "Income above Youth IRS threshold - €150,000 with 1st year benefits",
    observations: "Very high income where IAS multiplier limits discount significantly",
    params: {
      income: 150000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Income above Youth IRS threshold - €200,000 with 2nd year benefits",
    observations: "Extreme high income - testing discount limits with 75% discount",
    params: {
      income: 200000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // Transition between benefit years - comparing adjacent years
  {
    name: "Year transition: 1st to 2nd year comparison with €20,000 income",
    observations: "Comparing 1st year (100%) vs 2nd year (75%) discount impact",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Year transition: 4th to 5th year comparison with €30,000 income",
    observations: "Comparing 4th year (75%) vs 5th year (50%) discount reduction",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 5,
    },
  },
  {
    name: "Year transition: 7th to 8th year comparison with €25,000 income",
    observations: "Comparing 7th year (50%) vs 8th year (25%) discount reduction",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 8,
    },
  },

  // Youth IRS + RNH combinations
  {
    name: "Youth IRS 1st year + RNH with €40,000 income",
    observations: "Combining maximum Youth IRS benefits with RNH regime",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Youth IRS 2nd year + RNH with €50,000 income",
    observations: "Combining 75% Youth IRS discount with RNH regime",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Youth IRS 5th year + RNH with €60,000 income",
    observations: "Combining 50% Youth IRS discount with RNH regime",
    params: {
      income: 60000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 5,
    },
  },

  // Youth IRS with different income frequencies
  {
    name: "Youth IRS 1st year with monthly income €2,000",
    observations: "Monthly frequency with maximum Youth IRS benefits - €24,000/year",
    params: {
      income: 2000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Youth IRS 2nd year with daily rate €100 and 30 days off",
    observations: "Daily frequency with 75% Youth IRS discount - ~€33,500/year",
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 30,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // Youth IRS with expenses
  {
    name: "Youth IRS 1st year with €30,000 income and €5,000 expenses",
    observations: "Maximum Youth IRS benefits combined with organized accounting expenses",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 5000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Youth IRS 2nd year with €40,000 income and €8,000 expenses",
    observations: "75% Youth IRS discount combined with high organized expenses",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 8000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
];

