import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const disabilityScenarios: TestScenario[] = [
  // Married 2 holders with disabled spouse and 2 dependents scenarios
  {
    name: "Married 2 holders with disabled spouse and 2 dependents in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: false,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 2,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with disabled spouse and 2 dependents in Continente with average salary", 
    observations: `
      To calculate the tax for this person, it doesn't matter if wife has disability or not,
      since she's also a holder, which means she has its own income and will pay less taxes.
      If the person was the only holder, then they would pay less
    `,
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 2,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with disabled spouse and 2 dependents in Continente with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: false,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 2,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
];