import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const dependentsDisabilityScenarios: TestScenario[] = [
  // Single person with 1 disabled dependent scenarios
  {
    name: "Single person with 1 disabled dependent in Continent with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 1,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 1 disabled dependent in Continent with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 1,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 1 disabled dependent in Continent with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 1,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Single person with 2 dependents where 1 is disabled scenarios
  {
    name: "Single person with 2 dependents where 1 is disabled in Continent with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 2 dependents where 1 is disabled in Continent with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 2 dependents where 1 is disabled in Continent with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Single person with 2 dependents where both are disabled scenarios
  {
    name: "Single person with 2 dependents where both are disabled in Continent with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 2 dependents where both are disabled in Continent with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 2 dependents where both are disabled in Continent with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 2,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Single person with 3+ dependents where 1 is disabled scenarios
  {
    name: "Single person with 3+ dependents where 1 is disabled in Continent with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 3+ dependents where 1 is disabled in Continent with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 3+ dependents where 1 is disabled in Continent with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 1,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 1,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Single person with 3+ dependents where 2 are disabled scenarios
  {
    name: "Single person with 3+ dependents where 2 are disabled in Continent with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 3+ dependents where 2 are disabled in Continent with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 3+ dependents where 2 are disabled in Continent with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Single person with 3+ dependents where all are disabled scenarios
  {
    name: "Single person with 3+ dependents where all are disabled in Continent with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 3,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 3,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 3+ dependents where all are disabled in Continent with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 3,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 3,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with 3+ dependents where all are disabled in Continent with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 3,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 3,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 3,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
];
