import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const married1HolderDisabilitySpouse2DependentsBothDisabledScenarios: TestScenario[] = [
  // Married 1 holder with disability and disabled spouse with 2 dependents where both are disabled scenarios
  {
    name: "Married 1 holder with disability and disabled spouse and 2 dependents where both are disabled in Continent with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and 2 dependents where both are disabled in Continent with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and 2 dependents where both are disabled in Continent with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: true,
      number_of_dependents_with_disability: 2,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 2,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

];
