import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const personDisabilitySpouseDisabilityScenarios: TestScenario[] = [
  // Married 1 holder with disability and disabled spouse and no dependents scenarios
  {
    name: "Married 1 holder with disability and disabled spouse and no dependents in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and no dependents in Continente with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and no dependents in Continente with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 1 holder with disability and disabled spouse and 1 dependent scenarios
  {
    name: "Married 1 holder with disability and disabled spouse and 1 dependent in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 1,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and 1 dependent in Continente with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 1,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and 1 dependent in Continente with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 1,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 1 holder with disability and disabled spouse and 2 dependents scenarios
  {
    name: "Married 1 holder with disability and disabled spouse and 2 dependents in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and 2 dependents in Continente with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and 2 dependents in Continente with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 1 holder with disability and disabled spouse and 3+ dependents scenarios
  {
    name: "Married 1 holder with disability and disabled spouse and 3+ dependents in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 3,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and 3+ dependents in Continente with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 3,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with disability and disabled spouse and 3+ dependents in Continente with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 3,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 2 holders with disability and disabled spouse and no dependents scenarios
  {
    name: "Married 2 holders with disability and disabled spouse and no dependents in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with disability and disabled spouse and no dependents in Continente with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with disability and disabled spouse and no dependents in Continente with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with disability and disabled spouse and 1 dependent in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 1,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  // Married 2 holders with disability and disabled spouse and 2 dependents scenarios
  {
    name: "Married 2 holders with disability and disabled spouse and 2 dependents in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  // Married 2 holders with disability and disabled spouse and 3+ dependents scenarios
  {
    name: "Married 2 holders with disability and disabled spouse and 3+ dependents in Continente with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 3,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },


];


// This tests are failing but I think it's because Doutor Finanças is using the wrong table for this scenario - they select table 1, when the person has disability - doesn't make sense.
export const personDisabilitySpouseDisabilityScenariosFAILING: TestScenario[] = [
  // Married 2 holders with disability and disabled spouse and 1 dependent scenarios
  {
    name: "Married 2 holders with disability and disabled spouse and 1 dependent in Continente with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 1,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with disability and disabled spouse and 1 dependent in Continente with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 1,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 1,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },


  {
    name: "Married 2 holders with disability and disabled spouse and 2 dependents in Continente with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with disability and disabled spouse and 2 dependents in Continente with high salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 2,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 2,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },


  {
    name: "Married 2 holders with disability and disabled spouse and 3+ dependents in Continente with average salary",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 3,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with disability and disabled spouse and 3+ dependents in Continente with high salary",
    observations: "This is failing but I think it's because Doutor Finanças is using the wrong table for this scenario - they select table 1, when the person has disability - doesn't make sense.",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 3,
      disability_above_60: true,
      spouse_has_disability: true,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: true,
      partnerDisabled: true,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: 3,
      numberOfDependentsDisabled: 0,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
]