import { FrequencyChoices } from "../../../../src/independent-worker/schemas";
import { IndependentWorkerTestScenario } from "../../types";

export const incomeFrequencyScenarios: IndependentWorkerTestScenario[] = [
  // Monthly Frequency Scenarios
  {
    name: "Low monthly income independent worker with €1,000/month",
    observations: "Low monthly income scenario - €12,000 yearly equivalent - testing lower income thresholds with monthly frequency",
    params: {
      income: 1000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "High monthly income independent worker with €4,000/month",
    observations: "High monthly income scenario - €48,000 yearly equivalent - testing higher income with monthly frequency",
    params: {
      income: 4000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Premium monthly income independent worker with €6,000/month",
    observations: "Premium monthly income scenario - €72,000 yearly equivalent - testing very high income with monthly frequency",
    params: {
      income: 6000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Daily Frequency Scenarios - Low Daily Rate
  {
    name: "Low daily rate independent worker with €50/day and 30 days off",
    observations: "Low daily rate scenario - €16,750 yearly equivalent (€50/day × 335 working days) - testing lower income with daily frequency",
    params: {
      income: 50,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 30,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Daily Frequency Scenarios - High Daily Rate
  {
    name: "High daily rate independent worker with €200/day and 30 days off",
    observations: "High daily rate scenario - €67,000 yearly equivalent (€200/day × 335 working days) - testing higher income with daily frequency",
    params: {
      income: 200,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 30,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Premium daily rate independent worker with €300/day and 15 days off",
    observations: "Premium daily rate scenario - €105,000 yearly equivalent (€300/day × 350 working days) - testing very high income with daily frequency and fewer days off",
    params: {
      income: 300,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 15,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Variable Days Off Scenarios - Testing different days off combinations
  {
    name: "Daily rate independent worker with €100/day and 0 days off",
    observations: "Daily rate with no days off - €36,500 yearly equivalent (€100/day × 365 days) - testing maximum working days scenario",
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Daily rate independent worker with €100/day and 15 days off",
    observations: "Daily rate with 15 days off - €35,000 yearly equivalent (€100/day × 350 working days) - testing minimal days off scenario",
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 15,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Daily rate independent worker with €100/day and 45 days off",
    observations: "Daily rate with 45 days off - €32,000 yearly equivalent (€100/day × 320 working days) - testing moderate days off scenario",
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 45,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Daily rate independent worker with €100/day and 60 days off",
    observations: "Daily rate with 60 days off - €30,500 yearly equivalent (€100/day × 305 working days) - testing high days off scenario",
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 60,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
];

