import { FrequencyChoices } from "../../../../src/independent-worker/schemas";
import { IndependentWorkerTestScenario } from "../../types";

export const expenseScenarios: IndependentWorkerTestScenario[] = [
  // ============================================================
  // DECLARED EXPENSES (ORGANIZED ACCOUNTING)
  // ============================================================
  // DECLARED EXPENSES (ORGANIZED ACCOUNTING)
  // ============================================================

  // Low expenses (€1,000) - testing when simplified regime is better
  {
    name: "Organized accounting with €1,000 expenses and €20,000 income",
    observations: "Low expenses - simplified regime (15% = €3,000) should be better",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 1000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Organized accounting with €1,000 expenses and €30,000 income",
    observations: "Low expenses with higher income - simplified (15% = €4,500) should be better",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 1000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // High expenses (€8,000) - testing when organized accounting is better
  {
    name: "Organized accounting with €8,000 expenses and €30,000 income",
    observations: "High expenses - organized (€8,000) better than simplified (15% = €4,500)",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 8000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Organized accounting with €8,000 expenses and €40,000 income",
    observations: "High expenses with higher income - organized (€8,000) vs simplified (15% = €6,000)",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 8000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Organized accounting with €8,000 expenses and €50,000 income",
    observations: "High expenses with high income - organized (€8,000) vs simplified (15% = €7,500)",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 8000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Maximum beneficial expenses scenarios
  {
    name: "Organized accounting with €12,000 expenses and €60,000 income",
    observations: "Large expenses - organized (€12,000) vs simplified (15% = €9,000)",
    params: {
      income: 60000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 12000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Organized accounting with €20,000 expenses and €80,000 income",
    observations: "Very large expenses - organized (€20,000) vs simplified (15% = €12,000)",
    params: {
      income: 80000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 20000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Expenses higher than simplified regime benefit (edge cases)
  {
    name: "Organized accounting with expenses exceeding 15% threshold - €4,000 on €20,000",
    observations: "Expenses €4,000 > simplified €3,000 - organized should be used",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 4000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Organized accounting with expenses exceeding 15% threshold - €6,000 on €30,000",
    observations: "Expenses €6,000 > simplified €4,500 - organized should be used",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 6000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // MIXED EXPENSE SCENARIOS - Comparison & Break-even
  // ============================================================

  // Comparing simplified vs organized for same income - break-even point analysis
  // At 15% expense rate, break-even for €20,000 is exactly €3,000 in expenses
  {
    name: "Break-even point: €3,000 expenses on €20,000 income (15% = €3,000)",
    observations: "Exact break-even - expenses equal simplified regime deduction",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 3000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Break-even point: €4,500 expenses on €30,000 income (15% = €4,500)",
    observations: "Exact break-even - expenses equal simplified regime deduction",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 4500,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Break-even point: €7,500 expenses on €50,000 income (15% = €7,500)",
    observations: "Exact break-even - expenses equal simplified regime deduction",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 7500,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Edge cases where organized becomes beneficial
  {
    name: "Just above break-even: €3,100 expenses on €20,000 income",
    observations: "Slightly above break-even - organized marginally better",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 3100,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Just below break-even: €2,900 expenses on €20,000 income",
    observations: "Slightly below break-even - simplified marginally better",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 2900,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Very high expenses scenarios
  {
    name: "Very high expenses: €15,000 on €50,000 income (30%)",
    observations: "Expenses 30% of income - significantly above 15% simplified",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 15000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Very high expenses: €25,000 on €100,000 income (25%)",
    observations: "Large business expenses on high income",
    params: {
      income: 100000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 25000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Monthly income with expenses
  {
    name: "Monthly income €3,000 with €5,000 yearly expenses",
    observations: "Monthly frequency with organized expenses - €36,000/year income",
    params: {
      income: 3000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 5000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Daily income with expenses
  {
    name: "Daily rate €150 with 30 days off and €6,000 yearly expenses",
    observations: "Daily frequency with organized expenses - ~€50,250/year income",
    params: {
      income: 150,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 30,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 6000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
];

