import { FrequencyChoices } from "../../../../src/independent-worker/schemas";
import { IndependentWorkerTestScenario } from "../../types";
import { YEAR_BUSINESS_DAYS } from "../../../../src/independent-worker/consts";

export const configurationScenarios: IndependentWorkerTestScenario[] = [
  // ============================================================
  // PARAMETER VALIDATION - Boundary Testing
  // ============================================================

  // Invalid income values - testing minimum valid income
  {
    name: "Minimum valid income: €0.01 (boundary test)",
    observations: "Testing absolute minimum valid income value",
    params: {
      income: 0.01,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Very small income: €1.00 (boundary test)",
    observations: "Testing very small but valid income",
    params: {
      income: 1.00,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Very large income: €200,000 (boundary test)",
    observations: "Testing very high income boundary",
    params: {
      income: 200000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Extremely large income: €500,000 (boundary test)",
    observations: "Testing maximum income boundary scenario",
    params: {
      income: 500000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Invalid frequency combinations - testing all valid frequencies
  {
    name: "Yearly frequency with zero days off (valid combination)",
    observations: "Testing yearly frequency - days off should be ignored",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Monthly frequency with zero days off (valid combination)",
    observations: "Testing monthly frequency - days off should be ignored",
    params: {
      income: 2000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Daily frequency with maximum valid days off (boundary test)",
    observations: `Testing daily frequency with maximum valid days off (${YEAR_BUSINESS_DAYS - 1})`,
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: YEAR_BUSINESS_DAYS - 1,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Daily frequency with high days off (247 days off)",
    observations: "Testing daily frequency with very high days off (boundary)",
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 247,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Invalid date ranges - testing edge dates
  {
    name: "Activity opening on January 1st, 2025 (edge date)",
    observations: "Testing activity opening on first day of year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: new Date("2025-01-01"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Activity opening on December 31st, 2024 (previous year)",
    observations: "Testing activity opening on last day of previous year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: new Date("2024-12-31"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Activity opening mid-year (June 15th, 2025)",
    observations: "Testing activity opening in middle of tax year",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: new Date("2025-06-15"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Invalid percentage values - testing boundary percentages
  {
    name: "Maximum SS discount: 25% (boundary test)",
    observations: "Testing maximum valid SS discount (25%)",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0.25,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Minimum SS discount: -25% (boundary test)",
    observations: "Testing minimum valid SS discount (-25%)",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: -0.25,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Year of Youth IRS: Year 1 (minimum valid)",
    observations: "Testing minimum valid year of Youth IRS (1) - income set to ensure positive taxable income after 100% discount",
    params: {
      income: 35000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Year of Youth IRS: Year 10 (maximum valid for 2025)",
    observations: "Testing maximum valid year of Youth IRS (10 for 2025)",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 10,
    },
  },

  // ============================================================
  // DEFAULT VALUE TESTING
  // ============================================================

  // All optional parameters with defaults - minimal required params only
  {
    name: "Minimal parameters: only income specified",
    observations: "Testing with only required parameter (income), all others use defaults",
    params: {
      income: 30000,
    },
  },
  {
    name: "Minimal parameters: income + frequency",
    observations: "Testing with income and frequency, all others use defaults",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Month,
    },
  },
  {
    name: "Minimal parameters: income + daily frequency + days off",
    observations: "Testing with income, daily frequency, and days off, all others use defaults",
    params: {
      income: 100,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 30,
    },
  },
  {
    name: "Partial parameters: income + SS discount",
    observations: "Testing with income and SS discount, all others use defaults",
    params: {
      income: 30000,
      ssDiscount: 0.1,
    },
  },
  {
    name: "Partial parameters: income + expenses",
    observations: "Testing with income and expenses, all others use defaults",
    params: {
      income: 30000,
      expenses: 5000,
    },
  },
  {
    name: "Partial parameters: income + RNH",
    observations: "Testing with income and RNH flag, all others use defaults",
    params: {
      income: 40000,
      rnh: true,
    },
  },
  {
    name: "Partial parameters: income + Youth IRS",
    observations: "Testing with income and Youth IRS flag, all others use defaults - income set to ensure positive taxable income after discount",
    params: {
      income: 35000,
      benefitsOfYouthIrs: true,
    },
  },
  {
    name: "Partial parameters: income + activity opening date",
    observations: "Testing with income and activity opening date, all others use defaults",
    params: {
      income: 30000,
      dateOfOpeningAcivity: new Date("2025-01-01"),
    },
  },
  {
    name: "Partial parameters: income + tax year",
    observations: "Testing with income and tax year, all others use defaults",
    params: {
      income: 30000,
      currentTaxRankYear: 2024,
    },
  },
  // ============================================================
  // COMPLEX COMBINATIONS
  // ============================================================

  // All benefits active simultaneously
  {
    name: "All benefits active: RNH + Youth IRS + First Year + SS Discount",
    observations: "Testing maximum complexity with all benefits active simultaneously",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0.25,
      maxExpensesTax: 15,
      expenses: 5000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: new Date("2025-01-01"),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "All benefits active: RNH + Youth IRS + First Year + Maximum SS Discount + Monthly Frequency",
    observations: "Testing maximum complexity with monthly frequency and maximum SS discount",
    params: {
      income: 4000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0.25,
      maxExpensesTax: 15,
      expenses: 6000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: new Date("2025-01-01"),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  // Conflicting parameter scenarios (that are still valid)
  {
    name: "Conflicting: RNH with Youth IRS (both tax benefits)",
    observations: "Testing RNH and Youth IRS together - both provide tax benefits",
    params: {
      income: 40000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Conflicting: High expenses with simplified regime (organized vs simplified)",
    observations: "Testing high expenses that exceed simplified regime benefit",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 10000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Conflicting: First year + Second year benefits (date-based)",
    observations: "Testing activity opening date that triggers first year benefits",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: new Date("2024-01-01"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Conflicting: Maximum SS discount with high income",
    observations: "Testing maximum SS discount (25%) with high income",
    params: {
      income: 100000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0.25,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Conflicting: RNH with maximum expenses",
    observations: "Testing RNH with maximum expenses (organized accounting)",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 15000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningAcivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

];

