import { FrequencyChoices } from "../../../../src/independent-worker/schemas";
import { IndependentWorkerTestScenario } from "../../types";

export const realWorldScenarios: IndependentWorkerTestScenario[] = [
  // ============================================================
  // COMMON FREELANCER PROFILES
  // ============================================================

  // Junior developer (€18,000/year, monthly payments)
  {
    name: "Junior developer - €18,000/year with monthly payments (€1,500/month)",
    observations: "Common entry-level freelancer profile - monthly retainer payments, standard simplified regime",
    params: {
      income: 1500,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Junior developer with Youth IRS benefits - €18,000/year monthly",
    observations: "Junior developer eligible for Youth IRS benefits (2nd year - 25% discount)",
    params: {
      income: 1500,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },

  // Senior developer (€45,000/year, daily rate)
  // €45,000 / (365 - 30 days off) = ~€134/day with 30 days off
  {
    name: "Senior developer - €45,000/year with daily rate (€134/day, 30 days off)",
    observations: "Experienced developer working on daily rate contracts, standard simplified regime",
    params: {
      income: 134,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 30,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Senior developer with organized expenses - €45,000/year daily rate",
    observations: "Senior developer with significant business expenses (equipment, software, training)",
    params: {
      income: 134,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 30,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 8000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Design consultant (€35,000/year, project-based)
  {
    name: "Design consultant - €35,000/year project-based (yearly income)",
    observations: "Design consultant working on project basis, standard simplified regime",
    params: {
      income: 35000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Design consultant with high expenses - €35,000/year",
    observations: "Design consultant with significant expenses (software licenses, equipment, workspace)",
    params: {
      income: 35000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 6000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Marketing consultant (€28,000/year, monthly retainer)
  {
    name: "Marketing consultant - €28,000/year with monthly retainer (€2,333/month)",
    observations: "Marketing consultant on monthly retainer, standard simplified regime",
    params: {
      income: 2333,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Marketing consultant with moderate expenses - €28,000/year monthly",
    observations: "Marketing consultant with business expenses (tools, subscriptions, travel)",
    params: {
      income: 2333,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 4000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // SEASONAL WORKERS
  // ============================================================

  // Tourism sector (high season/low season)
  // High season: 6 months at higher rate, Low season: 6 months at lower rate
  // Simulating high season scenario (€3,000/month for 6 months = €18,000/year equivalent)
  {
    name: "Tourism sector worker - High season (€3,000/month for 6 months)",
    observations: "Tourism worker during high season months - represents peak earning period",
    params: {
      income: 3000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  // Low season: €1,000/month for 6 months = €6,000/year equivalent
  {
    name: "Tourism sector worker - Low season (€1,000/month for 6 months)",
    observations: "Tourism worker during low season months - represents off-peak earning period",
    params: {
      income: 1000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Construction (weather-dependent work)
  // Active months: higher income, Inactive months: lower/no income
  // Simulating active construction period (€2,500/month for 8 months = €20,000/year equivalent)
  {
    name: "Construction worker - Active period (€2,500/month for 8 months)",
    observations: "Construction worker during active weather months - represents working period",
    params: {
      income: 2500,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Construction worker with equipment expenses - Active period",
    observations: "Construction worker with significant equipment and tool expenses",
    params: {
      income: 2500,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 5000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Agricultural (seasonal work patterns)
  // Harvest season: high income, Off-season: lower income
  // Simulating harvest season (€4,000/month for 4 months = €16,000/year equivalent)
  {
    name: "Agricultural worker - Harvest season (€4,000/month for 4 months)",
    observations: "Agricultural worker during harvest season - represents peak earning period",
    params: {
      income: 4000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  // Off-season: €800/month for 8 months = €6,400/year equivalent
  {
    name: "Agricultural worker - Off-season (€800/month for 8 months)",
    observations: "Agricultural worker during off-season months - represents maintenance period",
    params: {
      income: 800,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // ============================================================
  // CAREER TRANSITION SCENARIOS
  // ============================================================

  // Employee to freelancer transition
  // First year of activity - may have first year benefits
  {
    name: "Employee to freelancer transition - First year (€25,000/year)",
    observations: "Recently transitioned from employee to freelancer - first year of activity",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: new Date("2025-01-15"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Employee to freelancer transition - First year with expenses",
    observations: "Recently transitioned freelancer with initial setup expenses",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 3000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: new Date("2025-01-15"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Young professional starting out
  // Low income + Youth IRS benefits
  {
    name: "Young professional starting out - €15,000/year with Youth IRS (1st year)",
    observations: "Young freelancer starting career with Youth IRS benefits (50% discount in 1st year)",
    params: {
      income: 15000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: new Date("2025-01-15"),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Young professional starting out - €20,000/year with Youth IRS (2nd year)",
    observations: "Young freelancer in second year with Youth IRS benefits (25% discount)",
    params: {
      income: 20000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: new Date("2024-01-15"),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "Young professional starting out - €18,000/year monthly with Youth IRS",
    observations: "Young freelancer with monthly income and Youth IRS benefits",
    params: {
      income: 1500,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: new Date("2025-01-15"),
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },

  // Experienced professional going independent
  // Higher income, no youth benefits
  {
    name: "Experienced professional going independent - €50,000/year",
    observations: "Experienced professional transitioning to freelancing - higher income, no youth benefits",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: new Date("2025-01-15"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Experienced professional going independent - €50,000/year with RNH",
    observations: "Experienced professional with RNH status - 20% flat tax rate",
    params: {
      income: 50000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: true,
      rnhTax: 0.2,
      dateOfOpeningActivity: new Date("2025-01-15"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Experienced professional going independent - Daily rate (€200/day, 20 days off)",
    observations: "Experienced professional working on daily rate contracts",
    params: {
      income: 200,
      incomeFrequency: FrequencyChoices.Day,
      nrDaysOff: 20,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: new Date("2025-01-15"),
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },

  // Near-retirement freelancing
  // Older worker, no youth benefits, potentially lower income
  {
    name: "Near-retirement freelancer - €30,000/year",
    observations: "Older freelancer approaching retirement - standard regime, no youth benefits",
    params: {
      income: 30000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Near-retirement freelancer - €30,000/year with reduced workload",
    observations: "Older freelancer with reduced working days - monthly income reflecting part-time schedule",
    params: {
      income: 2000,
      incomeFrequency: FrequencyChoices.Month,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 0,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "Near-retirement freelancer - €25,000/year with organized expenses",
    observations: "Older freelancer with business expenses (office, equipment maintenance)",
    params: {
      income: 25000,
      incomeFrequency: FrequencyChoices.Year,
      nrDaysOff: 0,
      ssDiscount: 0,
      maxExpensesTax: 15,
      expenses: 4000,
      ssTax: 0.214,
      currentTaxRankYear: 2025,
      rnh: false,
      rnhTax: 0.2,
      dateOfOpeningActivity: null,
      benefitsOfYouthIrs: false,
      yearOfYouthIrs: 1,
    },
  },
];

