import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

// Doutor Finanças' IRS Jovem simulator targets the same /net-salary endpoint
// but uses processType: 4, operationType: 2 and adds two extra fields:
//   - apply_irs_jovem: "true" | "false"
//   - activity_start_year: "1" (yr 1) | "3" (yr 2-4) | "4" (yr 5-7) | "5" (yr 8-10)
//
// IMPORTANT: DF's IRS Jovem simulator pins the IAS to the latest year (2026)
// regardless of the `year` field, so scenarios use year 2026 for fair
// comparison. Saldo's youth-IRS cap respects the simulation year.

export const youthIrsScenarios: TestScenario[] = [
  {
    name: "IRS Jovem yr 1 (100%) — single, €1500, no twelfths, no meal card",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "0",
      meal_card_days: 22,
      year: "2026",
      month: "default",
      processType: 4,
      operationType: 2,
      apply_irs_jovem: "true",
      activity_start_year: "1",
    },
    saldoRequest: {
      year: 2026,
      income: 1500,
      married: false,
      numberOfHolders: 1,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      socialSecurityContributionRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 0,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 1,
    },
  },
  {
    name: "IRS Jovem yr 2-4 (75%) — single, €3000, no twelfths",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "0",
      meal_card_days: 22,
      year: "2026",
      month: "default",
      processType: 4,
      operationType: 2,
      apply_irs_jovem: "true",
      activity_start_year: "3",
    },
    saldoRequest: {
      year: 2026,
      income: 3000,
      married: false,
      numberOfHolders: 1,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      socialSecurityContributionRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 0,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 2,
    },
  },
  {
    name: "IRS Jovem yr 5-7 (50%) — single, €6000, no twelfths",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "6000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "0",
      meal_card_days: 22,
      year: "2026",
      month: "default",
      processType: 4,
      operationType: 2,
      apply_irs_jovem: "true",
      activity_start_year: "4",
    },
    saldoRequest: {
      year: 2026,
      income: 6000,
      married: false,
      numberOfHolders: 1,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      socialSecurityContributionRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 0,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 5,
    },
  },
  {
    name: "IRS Jovem yr 8-10 (25%) — single, €2500, no twelfths",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "2500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "0",
      meal_card_days: 22,
      year: "2026",
      month: "default",
      processType: 4,
      operationType: 2,
      apply_irs_jovem: "true",
      activity_start_year: "5",
    },
    saldoRequest: {
      year: 2026,
      income: 2500,
      married: false,
      numberOfHolders: 1,
      numberOfDependents: 0,
      numberOfDependentsDisabled: 0,
      socialSecurityContributionRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 0,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
      benefitsOfYouthIrs: true,
      yearOfYouthIrs: 8,
    },
  },
];
