import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const lunchAllowanceEdgeCasesScenarios: TestScenario[] = [
  // Cupon Mode Edge Cases - Single Person
  {
    name: "Single person with cupon lunch allowance exactly at tax-free limit (10.20€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with cupon lunch allowance just above tax-free limit (10.21€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.21",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.21,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with zero cupon lunch allowance in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "0.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 0,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with cupon lunch allowance at maximum working days (31 days) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 31,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 31,
    },
  },

  // Salary Mode Edge Cases - Single Person
  {
    name: "Single person with salary lunch allowance exactly at tax-free limit (6€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "cash",
      daily_meal_card_value: "6.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 6,
      lunchAllowanceMode: "salary",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with salary lunch allowance just above tax-free limit (6.01€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "cash",
      daily_meal_card_value: "6.01",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 6.01,
      lunchAllowanceMode: "salary",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with zero salary lunch allowance in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "cash",
      daily_meal_card_value: "0.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 0,
      lunchAllowanceMode: "salary",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with salary lunch allowance at maximum working days (31 days) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "cash",
      daily_meal_card_value: "6.00",
      meal_card_days: 31,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 6,
      lunchAllowanceMode: "salary",
      lunchAllowanceDaysCount: 31,
    },
  },

  // Married 1 holder scenarios - Cupon Mode Edge Cases
  {
    name: "Married 1 holder with cupon lunch allowance exactly at tax-free limit (10.20€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with cupon lunch allowance just above tax-free limit (10.21€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.21",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.21,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 1 holder scenarios - Salary Mode Edge Cases
  {
    name: "Married 1 holder with salary lunch allowance exactly at tax-free limit (6€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "cash",
      daily_meal_card_value: "6.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 6,
      lunchAllowanceMode: "salary",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with salary lunch allowance just above tax-free limit (6.01€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "cash",
      daily_meal_card_value: "6.01",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 6.01,
      lunchAllowanceMode: "salary",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 2 holders scenarios - Cupon Mode Edge Cases
  {
    name: "Married 2 holders with cupon lunch allowance exactly at tax-free limit (10.20€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with cupon lunch allowance just above tax-free limit (10.21€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.21",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.21,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 2 holders scenarios - Salary Mode Edge Cases
  {
    name: "Married 2 holders with salary lunch allowance exactly at tax-free limit (6€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "cash",
      daily_meal_card_value: "6.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 6,
      lunchAllowanceMode: "salary",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with salary lunch allowance just above tax-free limit (6.01€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "cash",
      daily_meal_card_value: "6.01",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 6.01,
      lunchAllowanceMode: "salary",
      lunchAllowanceDaysCount: 22,
    },
  },
];
