import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const singlePersonLunchAllowanceScenarios: TestScenario[] = [
  // Cupon Mode Scenarios - Single Person
  {
    name: "Single person with cupon lunch allowance at minimum daily value (0€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "0.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 0,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with cupon lunch allowance at standard daily value (10.20€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with cupon lunch allowance at maximum tax-free value (10.20€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with cupon lunch allowance above tax-free limit (15€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "15.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 15,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with cupon lunch allowance at high value (20€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "20.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 20,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with cupon lunch allowance for 20 working days in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 20,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 20,
    },
  },
  {
    name: "Single person with cupon lunch allowance for 22 working days in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with cupon lunch allowance for 25 working days in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 25,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 25,
    },
  },
];
