import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const dateRangeEdgeCasesScenarios: TestScenario[] = [
  // Scenarios spanning tax periods
  {
    name: "Single person spanning Jan-Jul 2025 (early period) in Continent",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1), // January 1, 2025
      dateEnd: new Date(2025, 6, 31), // July 31, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder spanning Aug-Sep 2025 in Continent",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "2000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "08",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 2000,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 7, 1), // August 1, 2025
      dateEnd: new Date(2025, 8, 30), // September 30, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Scenarios at exact period boundaries
  {
    name: "Single person at exact period boundary Jul 31 - Aug 1 2025 in Continent",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1200.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "08",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1200,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 7, 1), // August 1, 2025
      dateEnd: new Date(2025, 8, 30), // September 30, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Period-specific scenarios
  {
    name: "Single person Jan-Jul 2025 in Continent with minimum wage",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "900.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 900,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1), // January 1, 2025
      dateEnd: new Date(2025, 6, 31), // July 31, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder Jan-Jul 2025 in Azores with average salary",
    doutorFinancasRequest: {
      location: "acores",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "azores",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1), // January 1, 2025
      dateEnd: new Date(2025, 6, 31), // July 31, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders Jan-Jul 2025 in Madeira with high salary",
    doutorFinancasRequest: {
      location: "madeira",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "3000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 3000,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "madeira",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1), // January 1, 2025
      dateEnd: new Date(2025, 6, 31), // July 31, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person Aug-Sep 2025 in Continent",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1300.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "08",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1300,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 7, 1), // August 1, 2025
      dateEnd: new Date(2025, 8, 30), // September 30, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person Oct-Dec 2025 in Continent",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1100.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "10",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1100,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 9, 1), // October 1, 2025
      dateEnd: new Date(2025, 11, 31), // December 31, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
];

// Scenarios that are currently failing due to DR Financas not using updated tax tables
export const dateRangeEdgeCasesFailingScenarios: TestScenario[] = [
  {
    name: "Married 2 holders spanning Oct-Dec 2025 (late period) in Azores",
    observations: "DR Financas is not using the updated table here - using the Jan one",
    doutorFinancasRequest: {
      location: "acores",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "2500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "10",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 2500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "azores",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 9, 1), // October 1, 2025
      dateEnd: new Date(2025, 11, 31), // December 31, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder at exact period boundary Oct 1 - Dez 31 2025 in Madeira",
    observations: "DR Financas is not using the updated table here - using the Jan one",
    doutorFinancasRequest: {
      location: "madeira",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1800.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "10",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1800,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "madeira",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 9, 1), // October 1, 2025
      dateEnd: new Date(2025, 11, 31), // December 31, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder Aug-Sep 2025 in Azores",
    observations: "DR Financas is not using the updated table here - using the Jan one",
    doutorFinancasRequest: {
      location: "acores",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1600.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "08",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1600,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "azores",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 7, 1), // August 1, 2025
      dateEnd: new Date(2025, 8, 30), // September 30, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders Oct-Dec 2025 in Madeira",
    observations: "DR Financas is not using the updated table here - using the Jan one",
    doutorFinancasRequest: {
      location: "madeira",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "2200.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "10",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 2200,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "madeira",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 9, 1), // October 1, 2025
      dateEnd: new Date(2025, 11, 31), // December 31, 2025
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
];