import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const edgeCasesScenarios: TestScenario[] = [
  // Single person with exactly minimum wage (870€) in Continente
  {
    name: "Single person with exactly minimum wage (870€) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "870.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 870,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Single person with income just below first tax bracket in Continente (869€)
  {
    name: "Single person with income just below first tax bracket (869€) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "869.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 869,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Single person with income at first tax bracket threshold in Continente (870€)
  {
    name: "Single person with income at first tax bracket threshold (870€) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "870.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 870,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Single person with income just above first tax bracket threshold in Continente (871€)
  {
    name: "Single person with income just above first tax bracket threshold (871€) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "871.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 871,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 1 holder with exactly minimum wage threshold in Continente (957€)
  {
    name: "Married 1 holder with exactly minimum wage threshold (957€) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "957.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 957,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 1 holder with income just below first tax bracket in Continente (956€)
  {
    name: "Married 1 holder with income just below first tax bracket (956€) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "956.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 956,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 1 holder with income just above first tax bracket threshold in Continente (958€)
  {
    name: "Married 1 holder with income just above first tax bracket threshold (958€) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "958.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 958,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 2 holders with exactly minimum wage threshold in Continente (870€ each)
  {
    name: "Married 2 holders with exactly minimum wage threshold (870€ each) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "870.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 870,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 2 holders with income just below first tax bracket in Continente (869€ each)
  {
    name: "Married 2 holders with income just below first tax bracket (869€ each) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "869.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 869,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

  // Married 2 holders with income just above first tax bracket threshold in Continente (871€ each)
  {
    name: "Married 2 holders with income just above first tax bracket threshold (871€ each) in Continente",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "871.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 871,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continente",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
];
