import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const maximumIncomeScenarios: TestScenario[] = [
  // Single person with very high income scenarios
  {
    name: "Single person with very high income (5000€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "5000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 5000,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Single person with income at highest tax bracket (8000€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "SOL",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "8000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 8000,
      married: false,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: null,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  // Married 1 holder with very high income scenarios
  {
    name: "Married 1 holder with very high income (5000€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "5000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 5000,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with income at highest tax bracket (8000€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "8000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 8000,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  // Married 2 holders with very high income scenarios
  {
    name: "Married 2 holders with very high income (5000€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "5000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 5000,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 2 holders with income at highest tax bracket (8000€) in Continent",
    doutorFinancasRequest: {
      location: "continent",
      marital_status: "CAS2",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "8000.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 8000,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 2,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      dateStart: new Date(2025, 0, 1),
      dateEnd: new Date(2025, 6, 31),
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
];
