import { Twelfths } from "../../../../src/dependent-worker/schemas";
import { TestScenario } from "../../types";

export const married1HolderLunchAllowanceScenarios: TestScenario[] = [
  // Married 1 holder scenarios
  {
    name: "Married 1 holder with cupon lunch allowance at standard value in Continent",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "10.20",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 10.2,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },
  {
    name: "Married 1 holder with cupon lunch allowance above tax-free limit in Continent",
    doutorFinancasRequest: {
      location: "continente",
      marital_status: "CAS1",
      number_of_dependents: 0,
      disability_above_60: false,
      spouse_has_disability: false,
      dependents_have_disability: false,
      number_of_dependents_with_disability: 0,
      base_salary: "1500.00",
      extraordinary_compensation: "",
      other_irs_ss_income: "",
      other_irs_income: "",
      other_exempt_income: "",
      social_security_rate: 11,
      twelfths: " ",
      meal_card_type: "voucher_card",
      daily_meal_card_value: "15.00",
      meal_card_days: 22,
      year: "2025",
      month: "default",
      processType: 1,
      operationType: 1,
    },
    saldoRequest: {
      income: 1500,
      married: true,
      disabled: false,
      partnerDisabled: false,
      location: "continent",
      numberOfHolders: 1,
      numberOfDependents: null,
      numberOfDependentsDisabled: null,
      period: "2025-01-01_2025-07-31",
      socialSecurityTaxRate: 0.11,
      twelfths: Twelfths.NONE,
      lunchAllowanceDailyValue: 15,
      lunchAllowanceMode: "cupon",
      lunchAllowanceDaysCount: 22,
    },
  },

];
